module Country
  # http://www.inf.ufrgs.br/~cabral/Paises.html
  # http://www.iso.org/iso/country_codes/iso_3166_code_lists.htm
  ISO_3166_CODE_LIST = [
    [ "AF", "Afeganistão" ],
    [ "ZA", "África do Sul" ],
    [ "AL", "Albânia" ],
    [ "DE", "Alemanha" ],
    [ "DZ", "Algéria" ],
    [ "AD", "Andorra" ],
    [ "AO", "Angola" ],
    [ "AI", "Anguilla" ],
    [ "AQ", "Antártida" ],
    [ "AG", "Antígua e Barbuda" ],
    [ "AN", "Antilhas Holandesas" ],
    [ "SA", "Arábia Saudita" ],
    [ "AR", "Argentina" ],
    [ "AM", "Armênia" ],
    [ "AW", "Aruba" ],
    [ "AU", "Austrália" ],
    [ "AT", "Áustria" ],
    [ "AZ", "Azerbaijão" ],
    [ "BS", "Bahamas" ],
    [ "BH", "Bahrein" ],
    [ "BD", "Bangladesh" ],
    [ "BB", "Barbados" ],
    [ "BY", "Belarus" ],
    [ "BE", "Bélgica" ],
    [ "BZ", "Belize" ],
    [ "BJ", "Benin" ],
    [ "BM", "Bermudas" ],
    [ "BO", "Bolívia" ],
    [ "BA", "Bósnia-Herzegóvina" ],
    [ "BW", "Botsuana" ],
    [ "BR", "Brasil" ],
    [ "BN", "Brunei" ],
    [ "BG", "Bulgária" ],
    [ "BF", "Burkina Fasso" ],
    [ "BI", "Burundi" ],
    [ "BT", "Butão" ],
    [ "CV", "Cabo Verde" ],
    [ "CM", "Camarões" ],
    [ "KH", "Camboja" ],
    [ "CA", "Canadá" ],
    [ "KZ", "Cazaquistão" ],
    [ "TD", "Chade" ],
    [ "CL", "Chile" ],
    [ "CN", "China" ],
    [ "CY", "Chipre" ],
    [ "SG", "Cingapura" ],
    [ "CO", "Colômbia" ],
    [ "CG", "Congo" ],
    [ "KP", "Coréia do Norte" ],
    [ "KR", "Coréia do Sul" ],
    [ "CI", "Costa do Marfim" ],
    [ "CR", "Costa Rica" ],
    [ "HR", "Croácia (Hrvatska)" ],
    [ "CU", "Cuba" ],
    [ "DK", "Dinamarca" ],
    [ "DJ", "Djibuti" ],
    [ "DM", "Dominica" ],
    [ "EG", "Egito" ],
    [ "SV", "El Salvador" ],
    [ "AE", "Emirados Árabes Unidos" ],
    [ "EC", "Equador" ],
    [ "ER", "Eritréia" ],
    [ "SK", "Eslováquia" ],
    [ "SI", "Eslovênia" ],
    [ "ES", "Espanha" ],
    [ "US", "Estados Unidos" ],
    [ "EE", "Estônia" ],
    [ "ET", "Etiópia" ],
    [ "RU", "Federação Russa" ],
    [ "FJ", "Fiji" ],
    [ "PH", "Filipinas" ],
    [ "FI", "Finlândia" ],
    [ "FR", "França" ],
    [ "FX", "França Metropolitana" ],
    [ "GA", "Gabão" ],
    [ "GM", "Gâmbia" ],
    [ "GH", "Gana" ],
    [ "GE", "Geórgia" ],
    [ "GI", "Gibraltar" ],
    [ "GB", "Grã-Bretanha (Reino Unido, UK)" ],
    [ "GD", "Granada" ],
    [ "GR", "Grécia" ],
    [ "GL", "Groelândia" ],
    [ "GP", "Guadalupe" ],
    [ "GU", "Guam (Território dos Estados Unidos)" ],
    [ "GT", "Guatemala" ],
    [ "GY", "Guiana" ],
    [ "GF", "Guiana Francesa" ],
    [ "GN", "Guiné" ],
    [ "GQ", "Guiné Equatorial" ],
    [ "GW", "Guiné-Bissau" ],
    [ "HT", "Haiti" ],
    [ "NL", "Holanda" ],
    [ "HN", "Honduras" ],
    [ "HK", "Hong Kong" ],
    [ "HU", "Hungria" ],
    [ "YE", "Iêmen" ],
    [ "BV", "Ilha Bouvet (Território da Noruega)" ],
    [ "CX", "Ilha Natal" ],
    [ "PN", "Ilha Pitcairn" ],
    [ "RE", "Ilha Reunião" ],
    [ "KY", "Ilhas Cayman" ],
    [ "CC", "Ilhas Cocos" ],
    [ "KM", "Ilhas Comores" ],
    [ "CK", "Ilhas Cook" ],
    [ "FO", "Ilhas Faeroes" ],
    [ "FK", "Ilhas Falkland (Malvinas)" ],
    [ "GS", "Ilhas Geórgia do Sul e Sandwich do Sul" ],
    [ "HM", "Ilhas Heard e McDonald (Território da Austrália)" ],
    [ "MP", "Ilhas Marianas do Norte" ],
    [ "MH", "Ilhas Marshall" ],
    [ "UM", "Ilhas Menores dos Estados Unidos" ],
    [ "NF", "Ilhas Norfolk" ],
    [ "SC", "Ilhas Seychelles" ],
    [ "SB", "Ilhas Solomão" ],
    [ "SJ", "Ilhas Svalbard e Jan Mayen" ],
    [ "TK", "Ilhas Tokelau" ],
    [ "TC", "Ilhas Turks e Caicos" ],
    [ "VI", "Ilhas Virgens (Estados Unidos)" ],
    [ "VG", "Ilhas Virgens (Inglaterra)" ],
    [ "WF", "Ilhas Wallis e Futuna" ],
    [ "IN", "índia" ],
    [ "ID", "Indonésia" ],
    [ "IR", "Irã" ],
    [ "IQ", "Iraque" ],
    [ "IE", "Irlanda" ],
    [ "IS", "Islândia" ],
    [ "IL", "Israel" ],
    [ "IT", "Itália" ],
    [ "YU", "Iugoslávia" ],
    [ "JM", "Jamaica" ],
    [ "JP", "Japão" ],
    [ "JO", "Jordânia" ],
    [ "KE", "Kênia" ],
    [ "KI", "Kiribati" ],
    [ "KW", "Kuait" ],
    [ "LA", "Laos" ],
    [ "LV", "Látvia" ],
    [ "LS", "Lesoto" ],
    [ "LB", "Líbano" ],
    [ "LR", "Libéria" ],
    [ "LY", "Líbia" ],
    [ "LI", "Liechtenstein" ],
    [ "LT", "Lituânia" ],
    [ "LU", "Luxemburgo" ],
    [ "MO", "Macau" ],
    [ "MK", "Macedônia" ],
    [ "MG", "Madagascar" ],
    [ "MY", "Malásia" ],
    [ "MW", "Malaui" ],
    [ "MV", "Maldivas" ],
    [ "ML", "Mali" ],
    [ "MT", "Malta" ],
    [ "MA", "Marrocos" ],
    [ "MQ", "Martinica" ],
    [ "MU", "Maurício" ],
    [ "MR", "Mauritânia" ],
    [ "YT", "Mayotte" ],
    [ "MX", "México" ],
    [ "FM", "Micronésia" ],
    [ "MZ", "Moçambique" ],
    [ "MD", "Moldova" ],
    [ "MC", "Mônaco" ],
    [ "MN", "Mongólia" ],
    [ "MS", "Montserrat" ],
    [ "MM", "Myanma" ],
    [ "NA", "Namíbia" ],
    [ "NR", "Nauru" ],
    [ "NP", "Nepal" ],
    [ "NI", "Nicarágua" ],
    [ "NE", "Níger" ],
    [ "NG", "Nigéria" ],
    [ "NU", "Niue" ],
    [ "NO", "Noruega" ],
    [ "NC", "Nova Caledônia" ],
    [ "NZ", "Nova Zelândia" ],
    [ "OM", "Omã" ],
    [ "PW", "Palau" ],
    [ "PA", "Panamá" ],
    [ "PG", "Papua-Nova Guiné" ],
    [ "PK", "Paquistão" ],
    [ "PY", "Paraguai" ],
    [ "PE", "Peru" ],
    [ "PF", "Polinésia Francesa" ],
    [ "PL", "Polônia" ],
    [ "PR", "Porto Rico" ],
    [ "PT", "Portugal" ],
    [ "QA", "Qatar" ],
    [ "KG", "Quirguistão" ],
    [ "CF", "República Centro-Africana" ],
    [ "DO", "República Dominicana" ],
    [ "CZ", "República Tcheca" ],
    [ "RO", "Romênia" ],
    [ "RW", "Ruanda" ],
    [ "EH", "Saara Ocidental" ],
    [ "VC", "Saint Vincente e Granadinas" ],
    [ "AS", "Samoa Americana" ],
    [ "WS", "Samoa Ocidental" ],
    [ "SM", "San Marino" ],
    [ "SH", "Santa Helena" ],
    [ "LC", "Santa Lúcia" ],
    [ "KN", "São Cristóvão e Névis" ],
    [ "ST", "São Tomé e Príncipe" ],
    [ "SN", "Senegal" ],
    [ "SL", "Serra Leoa" ],
    [ "SY", "Síria" ],
    [ "SO", "Somália" ],
    [ "LK", "Sri Lanka" ],
    [ "PM", "St. Pierre and Miquelon" ],
    [ "SZ", "Suazilândia" ],
    [ "SD", "Sudão" ],
    [ "SE", "Suécia" ],
    [ "CH", "Suíça" ],
    [ "SR", "Suriname" ],
    [ "TJ", "Tadjiquistão" ],
    [ "TH", "Tailândia" ],
    [ "TW", "Taiwan" ],
    [ "TZ", "Tanzânia" ],
    [ "IO", "Território Britânico do Oceano índico" ],
    [ "TF", "Territórios do Sul da França" ],
    [ "TP", "Timor Leste" ],
    [ "TG", "Togo" ],
    [ "TO", "Tonga" ],
    [ "TT", "Trinidad and Tobago" ],
    [ "TN", "Tunísia" ],
    [ "TM", "Turcomenistão" ],
    [ "TR", "Turquia" ],
    [ "TV", "Tuvalu" ],
    [ "UA", "Ucrânia" ],
    [ "UG", "Uganda" ],
    [ "UY", "Uruguai" ],
    [ "UZ", "Uzbequistão" ],
    [ "VU", "Vanuatu" ],
    [ "VA", "Vaticano" ],
    [ "VE", "Venezuela" ],
    [ "VN", "Vietnã" ],
    [ "ZR", "Zaire" ],
    [ "ZM", "Zâmbia" ],
    [ "ZW", "Zimbábue" ]
  ]

  def self.find_by_id(id)
    found = ISO_3166_CODE_LIST.select { |j| j[0]==id.to_s.upcase }
    found.length > 0 ? found[0][1] : nil
  end

  def self.find_by_name(name)
    found = ISO_3166_CODE_LIST.select { |j| j[1].to_s.upcase==name.to_s.upcase }
    found.length > 0 ? found[0][0] : nil
  end

  def self.all
    ISO_3166_CODE_LIST.map { |j| { :id => j[0], :name => j[1] } }
  end

  def self.keys
    ISO_3166_CODE_LIST.map { |j| j[0] }
  end

  def self.values
    ISO_3166_CODE_LIST.map { |j| j[1] }
  end
end
